### ISSUE TITLE
question: new version publish

### ISSUE THREAD

**Issue by jjangga0214** [fimuxd/GITGET#64]
Hi!

I've been waiting for a new version to be published soon, especially because of #62.

When would it be on the App Store?

Thanks :)

**Comment by fimuxd** [comment]
New version 23.15.0 will be prepared with TestFlight.
Even invalid username error (#62) is resolved, it's difficult to upload GITGET to AppStore. 
This is because the app was rejected by Apple for having too few features other than widgets 😅 

I cannot ideate and develop additional features right now.
So I would like to leave TestFlight link soon.

**Comment by fimuxd** [comment]
[TESTFLIGHT 링크](https://testflight.apple.com/join/3WGUZCMd)입니다. 
자세한 사정은 [Wiki](https://github.com/fimuxd/GITGET/wiki/To.-GITGET-Lovers)에 적어두었습니다. 🙇🏽
